#!/usr/bin/python3
def retrieve_el(list_, index):
    for i in range(len(list_)):
        if i < 0 or i > len(list_)-1:
            return None
        elif i == index:
            return f"The element retrieved is {list_[i]}"


lst = [5, 4, 3, 2, 1]
ind = 2
print(retrieve_el([5, 4, 3, 2, 1], 2))
print(retrieve_el([5, 4, 3, 2, 1], 0))
print(retrieve_el([5, 4, 3, 2, 1], -1))
print(retrieve_el([5, 4, 3, 2, 1], 5))
